menu:
    Blog: /
    Projects: projects/
    About: https://www.linkedin.com/in/izzuddinahsanujunda
    Archive: archives/

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: claymcleod 
disqus:

# Analytics
 ga: UA-168380075-2

# Copyright Infomation
startyear: 2020

# Image Credits
enable_image_credit: true 
